03-04-2023 15:27:32 - INFO - ENV variables ready
03-04-2023 15:27:35 - INFO - Connected to DB
03-04-2023 15:27:38 - INFO - Connected to DB
03-04-2023 15:27:41 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
03-04-2023 15:27:41 - INFO - [33mPress CTRL+C to quit[0m
03-04-2023 15:27:41 - INFO -  * Restarting with stat
03-04-2023 15:27:42 - INFO - ENV variables ready
03-04-2023 15:27:45 - INFO - Connected to DB
03-04-2023 15:27:48 - INFO - Connected to DB
03-04-2023 15:27:51 - WARNING -  * Debugger is active!
03-04-2023 15:27:51 - INFO -  * Debugger PIN: 102-491-821
03-04-2023 15:29:24 - INFO -  * Detected change in 'C:\\Users\\rkantha\\Documents\\GitHub\\OG_ACEE_TASK_AUTOMATIOJN\\ACEE_task_automation\\backend\\app.py', reloading
03-04-2023 15:30:45 - INFO - ENV variables ready
03-04-2023 15:30:48 - INFO - Connected to DB
03-04-2023 15:30:51 - INFO - Connected to DB
03-04-2023 15:30:53 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
03-04-2023 15:30:53 - INFO - [33mPress CTRL+C to quit[0m
03-04-2023 15:30:54 - INFO -  * Restarting with stat
03-04-2023 15:30:54 - INFO - ENV variables ready
03-04-2023 15:30:57 - INFO - Connected to DB
03-04-2023 15:31:00 - INFO - Connected to DB
03-04-2023 15:31:02 - WARNING -  * Debugger is active!
03-04-2023 15:31:03 - INFO -  * Debugger PIN: 102-491-821
03-04-2023 15:31:13 - INFO - 127.0.0.1 - - [03/Apr/2023 15:31:13] "[35m[1mPOST /insertIntoDatabase HTTP/1.1[0m" 500 -
03-04-2023 15:32:39 - INFO - ENV variables ready
03-04-2023 15:32:42 - INFO - Connected to DB
03-04-2023 15:32:45 - INFO - Connected to DB
03-04-2023 15:32:47 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
03-04-2023 15:32:47 - INFO - [33mPress CTRL+C to quit[0m
03-04-2023 15:32:48 - INFO -  * Restarting with stat
03-04-2023 15:32:48 - INFO - ENV variables ready
03-04-2023 15:32:51 - INFO - Connected to DB
03-04-2023 15:32:54 - INFO - Connected to DB
03-04-2023 15:32:56 - WARNING -  * Debugger is active!
03-04-2023 15:32:57 - INFO -  * Debugger PIN: 102-491-821
03-04-2023 15:33:07 - INFO - 127.0.0.1 - - [03/Apr/2023 15:33:07] "[35m[1mPOST /insertIntoDatabase HTTP/1.1[0m" 500 -
03-04-2023 15:34:09 - INFO - ENV variables ready
03-04-2023 15:34:12 - INFO - Connected to DB
03-04-2023 15:34:15 - INFO - Connected to DB
03-04-2023 15:34:17 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
03-04-2023 15:34:17 - INFO - [33mPress CTRL+C to quit[0m
03-04-2023 15:34:18 - INFO -  * Restarting with stat
03-04-2023 15:34:18 - INFO - ENV variables ready
03-04-2023 15:34:21 - INFO - Connected to DB
03-04-2023 15:34:24 - INFO - Connected to DB
03-04-2023 15:34:27 - WARNING -  * Debugger is active!
03-04-2023 15:34:27 - INFO -  * Debugger PIN: 102-491-821
03-04-2023 15:35:12 - INFO - API: /insertIntoDatabase MSG: Data added successfully
03-04-2023 15:35:12 - INFO - 127.0.0.1 - - [03/Apr/2023 15:35:12] "POST /insertIntoDatabase HTTP/1.1" 200 -
03-04-2023 15:35:42 - INFO - API: /insertIntoDatabase MSG: Data added successfully
03-04-2023 15:35:42 - INFO - 127.0.0.1 - - [03/Apr/2023 15:35:42] "POST /insertIntoDatabase HTTP/1.1" 200 -
03-04-2023 15:38:28 - DEBUG - Starting new HTTPS connection (1): console.privilegecloud.cyberark.com:443
03-04-2023 15:38:28 - DEBUG - Starting new HTTPS connection (1): console.privilegecloud.cyberark.comfiles:443
03-04-2023 15:38:29 - ERROR - INSTALL_PSM_CERTIFICATE MSG: Error occured while installing PSM certs - HTTPSConnectionPool(host='console.privilegecloud.cyberark.comfiles', port=443): Max retries exceeded with url: /v1/installPsmCertificate/d33962a1-05e5-4497-b776-58e93718d274 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002AA3BB51610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
03-04-2023 15:38:29 - ERROR - API: /approveRequest MSG: Error occured while retrieving data from the database - 'status'
03-04-2023 15:38:29 - INFO - 127.0.0.1 - - [03/Apr/2023 15:38:29] "POST /approveRequest HTTP/1.1" 200 -
03-04-2023 15:38:29 - DEBUG - https://console.privilegecloud.cyberark.com:443 "GET /tenants/v1/tasks?mainObjectId=d33962a1-05e5-4497-b776-58e93718d274 HTTP/1.1" 401 54
03-04-2023 15:38:29 - INFO - GET_TASK_STATUS MSG: Task status fetch SUCCESSFUL
03-04-2023 15:43:00 - INFO -  * Detected change in 'C:\\Users\\rkantha\\Documents\\GitHub\\OG_ACEE_TASK_AUTOMATIOJN\\ACEE_task_automation\\backend\\pcloudapis.py', reloading
03-04-2023 15:43:00 - INFO -  * Restarting with stat
03-04-2023 15:43:00 - INFO - ENV variables ready
03-04-2023 15:43:04 - INFO - Connected to DB
03-04-2023 15:43:07 - INFO - Connected to DB
03-04-2023 15:43:09 - WARNING -  * Debugger is active!
03-04-2023 15:43:09 - INFO -  * Debugger PIN: 102-491-821
03-04-2023 15:43:45 - INFO -  * Detected change in 'C:\\Users\\rkantha\\Documents\\GitHub\\OG_ACEE_TASK_AUTOMATIOJN\\ACEE_task_automation\\backend\\pcloudapis.py', reloading
03-04-2023 15:44:10 - INFO - ENV variables ready
03-04-2023 15:44:14 - INFO - Connected to DB
03-04-2023 15:44:16 - INFO - Connected to DB
03-04-2023 15:44:19 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
03-04-2023 15:44:19 - INFO - [33mPress CTRL+C to quit[0m
03-04-2023 15:44:19 - INFO -  * Restarting with stat
03-04-2023 15:44:20 - INFO - ENV variables ready
03-04-2023 15:44:23 - INFO - Connected to DB
03-04-2023 15:44:26 - INFO - Connected to DB
03-04-2023 15:44:28 - WARNING -  * Debugger is active!
03-04-2023 15:44:29 - INFO -  * Debugger PIN: 102-491-821
03-04-2023 15:44:38 - DEBUG - Starting new HTTPS connection (1): console.privilegecloud.cyberark.com:443
03-04-2023 15:44:38 - DEBUG - Starting new HTTPS connection (1): console.privilegecloud.cyberark.comfiles:443
03-04-2023 15:44:38 - ERROR - INSTALL_PSM_CERTIFICATE MSG: Error occured while installing PSM certs - HTTPSConnectionPool(host='console.privilegecloud.cyberark.comfiles', port=443): Max retries exceeded with url: /v1/installPsmCertificate/d33962a1-05e5-4497-b776-58e93718d274 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000217E49C62D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
03-04-2023 15:44:38 - ERROR - API: /approveRequest MSG: Error occured while retrieving data from the database - 'status'
03-04-2023 15:44:38 - INFO - 127.0.0.1 - - [03/Apr/2023 15:44:38] "POST /approveRequest HTTP/1.1" 200 -
03-04-2023 15:44:39 - DEBUG - https://console.privilegecloud.cyberark.com:443 "GET /tenants/v1/tasks?mainObjectId=d33962a1-05e5-4497-b776-58e93718d274 HTTP/1.1" 401 54
03-04-2023 15:44:39 - INFO - GET_TASK_STATUS MSG: Task status fetch SUCCESSFUL
03-04-2023 15:46:33 - INFO -  * Detected change in 'C:\\Users\\rkantha\\Documents\\GitHub\\OG_ACEE_TASK_AUTOMATIOJN\\ACEE_task_automation\\backend\\helper2.py', reloading
03-04-2023 15:46:33 - INFO -  * Restarting with stat
03-04-2023 15:46:33 - INFO - ENV variables ready
03-04-2023 15:46:36 - INFO - Connected to DB
03-04-2023 15:46:39 - INFO - Connected to DB
03-04-2023 15:46:41 - WARNING -  * Debugger is active!
03-04-2023 15:46:42 - INFO -  * Debugger PIN: 102-491-821
03-04-2023 15:48:01 - INFO - ENV variables ready
03-04-2023 15:48:04 - INFO - Connected to DB
03-04-2023 15:48:07 - INFO - Connected to DB
03-04-2023 15:48:10 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
03-04-2023 15:48:10 - INFO - [33mPress CTRL+C to quit[0m
03-04-2023 15:48:10 - INFO -  * Restarting with stat
03-04-2023 15:48:11 - INFO - ENV variables ready
03-04-2023 15:48:14 - INFO - Connected to DB
03-04-2023 15:48:17 - INFO - Connected to DB
03-04-2023 15:48:19 - WARNING -  * Debugger is active!
03-04-2023 15:48:20 - INFO -  * Debugger PIN: 102-491-821
03-04-2023 15:48:29 - DEBUG - Starting new HTTPS connection (1): console.privilegecloud.cyberark.com:443
03-04-2023 15:48:29 - DEBUG - Starting new HTTPS connection (1): console.privilegecloud.cyberark.comfiles:443
03-04-2023 15:48:29 - ERROR - INSTALL_PSM_CERTIFICATE MSG: Error occured while installing PSM certs - HTTPSConnectionPool(host='console.privilegecloud.cyberark.comfiles', port=443): Max retries exceeded with url: /v1/installPsmCertificate/d33962a1-05e5-4497-b776-58e93718d274 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000024B15176350>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
03-04-2023 15:48:29 - ERROR - API: /approveRequest MSG: Error occured while retrieving data from the database - 'status'
03-04-2023 15:48:29 - INFO - 127.0.0.1 - - [03/Apr/2023 15:48:29] "POST /approveRequest HTTP/1.1" 200 -
03-04-2023 15:48:29 - DEBUG - https://console.privilegecloud.cyberark.com:443 "GET /tenants/v1/tasks?mainObjectId=d33962a1-05e5-4497-b776-58e93718d274 HTTP/1.1" 200 None
03-04-2023 15:48:29 - INFO - GET_TASK_STATUS MSG: Task status fetch SUCCESSFUL
03-04-2023 15:48:31 - ERROR - INSTALL_PSM_CERTIFICATE MSG: Error occured while installing PSM certs - 'Content-Type'
03-04-2023 15:50:25 - INFO -  * Detected change in 'C:\\Users\\rkantha\\Documents\\GitHub\\OG_ACEE_TASK_AUTOMATIOJN\\ACEE_task_automation\\backend\\pcloudapis.py', reloading
03-04-2023 15:50:25 - INFO -  * Restarting with stat
03-04-2023 15:50:26 - INFO - ENV variables ready
03-04-2023 15:50:29 - INFO - Connected to DB
03-04-2023 15:50:32 - INFO - Connected to DB
03-04-2023 15:50:34 - WARNING -  * Debugger is active!
03-04-2023 15:50:35 - INFO -  * Debugger PIN: 102-491-821
03-04-2023 15:50:56 - INFO -  * Detected change in 'C:\\Users\\rkantha\\Documents\\GitHub\\OG_ACEE_TASK_AUTOMATIOJN\\ACEE_task_automation\\backend\\pcloudapis.py', reloading
03-04-2023 15:51:12 - INFO - ENV variables ready
03-04-2023 15:51:16 - INFO - Connected to DB
03-04-2023 15:51:19 - INFO - Connected to DB
03-04-2023 15:51:21 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
03-04-2023 15:51:21 - INFO - [33mPress CTRL+C to quit[0m
03-04-2023 15:51:21 - INFO -  * Restarting with stat
03-04-2023 15:51:22 - INFO - ENV variables ready
03-04-2023 15:51:24 - INFO - ENV variables ready
03-04-2023 15:51:27 - INFO - Connected to DB
03-04-2023 15:51:31 - INFO - Connected to DB
03-04-2023 15:51:33 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
03-04-2023 15:51:33 - INFO - [33mPress CTRL+C to quit[0m
03-04-2023 15:51:33 - INFO -  * Restarting with stat
03-04-2023 15:51:34 - INFO - ENV variables ready
03-04-2023 15:51:37 - INFO - Connected to DB
03-04-2023 15:51:40 - INFO - Connected to DB
03-04-2023 15:51:42 - WARNING -  * Debugger is active!
03-04-2023 15:51:42 - INFO -  * Debugger PIN: 102-491-821
03-04-2023 15:51:52 - DEBUG - Starting new HTTPS connection (1): console.privilegecloud.cyberark.com:443
03-04-2023 15:51:52 - DEBUG - Starting new HTTPS connection (1): console.privilegecloud.cyberark.comfiles:443
03-04-2023 15:51:52 - ERROR - INSTALL_PSM_CERTIFICATE MSG: Error occured while installing PSM certs - HTTPSConnectionPool(host='console.privilegecloud.cyberark.comfiles', port=443): Max retries exceeded with url: /v1/installPsmCertificate/d33962a1-05e5-4497-b776-58e93718d274 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000023145B78F90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
03-04-2023 15:51:52 - ERROR - API: /approveRequest MSG: Error occured while retrieving data from the database - 'status'
03-04-2023 15:51:52 - INFO - 127.0.0.1 - - [03/Apr/2023 15:51:52] "POST /approveRequest HTTP/1.1" 200 -
03-04-2023 15:51:53 - DEBUG - https://console.privilegecloud.cyberark.com:443 "GET /tenants/v1/tasks?mainObjectId=d33962a1-05e5-4497-b776-58e93718d274 HTTP/1.1" 200 None
03-04-2023 15:51:53 - INFO - GET_TASK_STATUS MSG: Task status fetch SUCCESSFUL
03-04-2023 15:51:54 - ERROR - INSTALL_PSM_CERTIFICATE MSG: Error occured while installing PSM certs - 'Content-Type'
03-04-2023 15:52:24 - INFO -  * Detected change in 'C:\\Users\\rkantha\\Documents\\GitHub\\OG_ACEE_TASK_AUTOMATIOJN\\ACEE_task_automation\\backend\\helper2.py', reloading
03-04-2023 15:52:24 - INFO -  * Restarting with stat
03-04-2023 15:52:25 - INFO - ENV variables ready
03-04-2023 15:52:28 - INFO - Connected to DB
03-04-2023 15:52:31 - INFO - Connected to DB
03-04-2023 15:52:33 - WARNING -  * Debugger is active!
03-04-2023 15:52:33 - INFO -  * Debugger PIN: 102-491-821
03-04-2023 15:52:54 - INFO -  * Detected change in 'C:\\Users\\rkantha\\Documents\\GitHub\\OG_ACEE_TASK_AUTOMATIOJN\\ACEE_task_automation\\backend\\helper2.py', reloading
03-04-2023 15:53:23 - INFO - ENV variables ready
03-04-2023 15:53:26 - INFO - Connected to DB
03-04-2023 15:53:29 - INFO - Connected to DB
03-04-2023 15:53:31 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
03-04-2023 15:53:31 - INFO - [33mPress CTRL+C to quit[0m
03-04-2023 15:53:32 - INFO -  * Restarting with stat
03-04-2023 15:53:32 - INFO - ENV variables ready
03-04-2023 15:53:36 - INFO - Connected to DB
03-04-2023 15:53:38 - INFO - Connected to DB
03-04-2023 15:53:41 - WARNING -  * Debugger is active!
03-04-2023 15:53:41 - INFO -  * Debugger PIN: 102-491-821
03-04-2023 15:53:50 - DEBUG - Starting new HTTPS connection (1): console.privilegecloud.cyberark.com:443
03-04-2023 15:53:50 - DEBUG - Starting new HTTPS connection (1): console.privilegecloud.cyberark.comfiles:443
03-04-2023 15:53:50 - ERROR - INSTALL_PSM_CERTIFICATE MSG: Error occured while installing PSM certs - HTTPSConnectionPool(host='console.privilegecloud.cyberark.comfiles', port=443): Max retries exceeded with url: /v1/installPsmCertificate/d33962a1-05e5-4497-b776-58e93718d274 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000217BBDAA410>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
03-04-2023 15:53:50 - ERROR - API: /approveRequest MSG: Error occured while retrieving data from the database - 'status'
03-04-2023 15:53:50 - INFO - 127.0.0.1 - - [03/Apr/2023 15:53:50] "POST /approveRequest HTTP/1.1" 200 -
03-04-2023 15:53:51 - DEBUG - https://console.privilegecloud.cyberark.com:443 "GET /tenants/v1/tasks?mainObjectId=d33962a1-05e5-4497-b776-58e93718d274 HTTP/1.1" 200 None
03-04-2023 15:53:51 - INFO - GET_TASK_STATUS MSG: Task status fetch SUCCESSFUL
03-04-2023 15:53:53 - ERROR - INSTALL_PSM_CERTIFICATE MSG: Error occured while installing PSM certs - 'Content-Type'
